###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = tofi-drun --drun-launch=true --prompt="apps:" -c ~/.config/tofi/config
$menu2 = tofi-run | sh
$power = $HOME/power.sh
$browser = zen-browser
$editor = zeditor
$settings = zeditor ~/dotfiles
